In [ ]:
import numpy as np 
import pandas as pd


In [ ]:
data=pd.read_csv("/content/weatherAUS (1).csv")

In [ ]:
data.head()

Date Location  MinTemp  ...  Temp3pm  RainToday  RainTomorrow
0  2008-12-01   Albury     13.4  ...     21.8         No            No
1  2008-12-02   Albury      7.4  ...     24.3         No            No
2  2008-12-03   Albury     12.9  ...     23.2         No            No
3  2008-12-04   Albury      9.2  ...     26.5         No            No
4  2008-12-05   Albury     17.5  ...     29.7         No            No

[5 rows x 23 columns]

In [ ]:
# ekhane nichhe data lekhha achhe [:[]] : tar mane holo every row []
# vitorem je list ota holo column index 
# ekahne amaara column index diyechhi 0 ke bad diyechhi karon ota amar lagbe na okane date ache 
# eirokom kore amra saiy column index gulo niyechhi je gulo amder dorkar  
# and x holo feature variable jarekahne traget column index add hoy ni 

X = data.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values

# ekahne sob y target variable mane sob thake last variable holo target variable python use last varible we can use  -1

Y = data.iloc[:,-1].values

#Y=data.iloc[:,21:].values

In [ ]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['PerthAirport' 8.0 24.9 ... 15.1 24.2 'No']
 ['PerthAirport' 10.2 26.6 ... 16.3 26.3 'No']
 ['PerthAirport' 8.4 25.8 ... nan nan nan]]


In [ ]:
# Y = data.iloc[:,-1].values eita korle amra 2d  list array petam na 
# data.iloc[:,21:].values etra holo slicing & slicing generate new list 

print(Y)

['No' 'No' 'No' ... 'No' 'No' nan]


In [ ]:
Y = Y.reshape(-1,1)

Y = data.iloc[:,-1] eta korle amra 1d list pabo but 1d list ke 2d te ki vabe cahnge korbo Y=Y.rashape(-1,1) print(Y) and you get 2d list

## Null values & delling with data

mane ekhane data te je gulo null values achhe se gilo ke tar most frequent value diyea repalce korbo jeta ke amra boli imputer eta data preproscing modhhe pore jemon label eoncoder o er moddhe pore amder ke google giye search korte hobe data preproscing tecnique 


In [ ]:
import sklearn
from sklearn.impute import SimpleImputer
imputer =SimpleImputer (missing_values=np.nan,strategy='most_frequent')
# eto ta korar por eta ke amra X Namd Y sobar jono korbo 
X= imputer.fit_transform(X)
Y = imputer.fit_transform(Y)

In [ ]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['PerthAirport' 8.0 24.9 ... 15.1 24.2 'No']
 ['PerthAirport' 10.2 26.6 ... 16.3 26.3 'No']
 ['PerthAirport' 8.4 25.8 ... 17.0 20.0 'No']]


In [ ]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


amara sobby jani je machin learning only suppurt numeric data not suppurt creectar type data string data eta ke amra ki vabe solve korbo seta dekte hobe r ektra kothha mone rakte hobe X[:,0] eta mane X = data.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values ekahene mara je gulo select korechhi ekhane 0 in dex mane x er 1 & 2 mane x er 1 index real data te jeta index chilo seta x er 2 mane tar 3 index 

#     X = data.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]]

#    index show in x [0,1,2,3,4,5,6,7,  8, 9,10,11,12,13,14,15,16,17,18]

# Encoding dtataset 

In [ ]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])
le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7])
le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])
le6 = LabelEncoder()
Y = le6.fit_transform(Y)


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(X)

[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [26 8.0 24.9 ... 15.1 24.2 0]
 [26 10.2 26.6 ... 16.3 26.3 0]
 [26 8.4 25.8 ... 17.0 20.0 0]]


In [ ]:
print(Y)

[0 0 0 ... 0 0 0]


# Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X=sc.fit_transform(X)

In [ ]:
print(X)

[[-1.48158564  0.23167655  0.02046735 ...  0.04246398  0.0794306
  -0.53584953]
 [-1.48158564 -0.73556101  0.34086738 ...  0.09070097  0.45602548
  -0.53584953]
 [-1.48158564  0.15107342  0.42824921 ...  0.70170294  0.29032373
  -0.53584953]
 ...
 [ 0.57239836 -0.63883725  0.31174011 ... -0.24695801  0.44096168
  -0.53584953]
 [ 0.57239836 -0.28418348  0.55932194 ... -0.05401002  0.75730138
  -0.53584953]
 [ 0.57239836 -0.57435475  0.44281284 ...  0.05854298 -0.19171771
  -0.53584953]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,
                                                 test_size=0.2,
                                                 random_state=0)

In [ ]:
print(X_train)

[[ 0.74356369  0.47348594  0.99623107 ...  0.66954494  1.11883246
  -0.53584953]
 [ 0.82914636 -1.70279856 -0.78053271 ... -0.53637999 -0.65869536
  -0.53584953]
 [ 1.00031169  1.44072349  0.86515833 ...  1.4574159   0.96819451
   1.86619554]
 ...
 [ 1.59939036  1.34399974  0.58844922 ...  1.00720392  0.63679102
  -0.53584953]
 [ 1.59939036  0.00598779 -0.88247817 ... -0.311274   -0.73401433
  -0.53584953]
 [-0.54017631 -0.31642473 -1.01355091 ... -0.77756498 -1.11060921
  -0.53584953]]


In [ ]:
print(Y_train)

[0 0 0 ... 0 0 0]


# Training Model

ekhane random forest classifire use korbo karon ekahne ans je 
asbe o and 1 yes or no and limited value jar we can use classifire 
we don't use regressor 

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifire = RandomForestClassifier(n_estimators=150,random_state=0)
classifire.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=150, random_state=0)

In [ ]:
classifire.score(X_train,Y_train)

0.9999368872806833

In [ ]:
print(Y_test)

[0 0 0 ... 0 0 0]


In [ ]:
y_pred = classifire.predict(X_test)

In [ ]:
print(y_pred)

[0 0 0 ... 0 0 0]


I need y predict in from yes or no not 0 and 1 tar jono amra opare je le funcation korechilum seta inverse korte hobe setaiy korle yes & no from convert hobe 

In [ ]:
y_pred =le6.inverse_transform(y_pred)

In [ ]:
print(y_pred)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [ ]:
Y_test = le6.inverse_transform(Y_test)

In [ ]:
print(Y_test)

['No' 'No' 'No' ... 'No' 'No' 'No']


ekhane nichhe 1d tahke 2d korahoyechhe 

In [ ]:
Y_test = Y_test.reshape(-1,1)
y_pred = y_pred.reshape(-1,1)

In [ ]:
df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','prediction of Rain'])

ekhane 'yes' holo Y_test, y_pred holo 'no'  are axis =1 holo "yes&no" ta eki place asa aki  column te asa r ki 

In [ ]:
print(df)

[['No' 'No']
 ['No' 'No']
 ['No' 'No']
 ...
 ['No' 'No']
 ['No' 'No']
 ['No' 'No']]


ekahne yes sojasuji thale no thakle prediction wrong 
and yes sojasoji yes thakle predition right

In [ ]:
print(dataframe)
dataframe.head(30)

      Rain on Tommorrow prediction of Rain
0                    No                 No
1                    No                 No
2                    No                 No
3                    No                 No
4                    No                 No
...                 ...                ...
23763                No                 No
23764                No                 No
23765                No                 No
23766                No                 No
23767                No                 No

[23768 rows x 2 columns]


Rain on Tommorrow prediction of Rain
0                 No                 No
1                 No                 No
2                 No                 No
3                 No                 No
4                 No                 No
5                 No                 No
6                 No                 No
7                 No                 No
8                 No                Yes
9                 No                 No
10                No                 No
11                No                 No
12                No                 No
13               Yes                 No
14                No                 No
15                No                 No
16                No                 No
17                No                 No
18                No                 No
19                No                 No
20                No                 No
21                No                 No
22                No                 No
23               Yes                 No
24                No                 No
25                No                 No
26                No                 No
27                No                Yes
28                No                 No
29                No                 No

# Calculating Accuracy

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8490407270279368

when we estimator is high then accuracy more better then this

ekhane eitar dara prediction  csv akta fil
redy korlum 

In [ ]:
dataframe.to_csv('prediction.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
